# Generated by Django 4.2.2 on 2023-07-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='name')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('token', models.CharField(max_length=256, unique=True, verbose_name='token')),
                ('lang', models.CharField(blank=True, default='RUS', max_length=5, verbose_name='language')),
                ('desc', models.CharField(blank=True, max_length=512, verbose_name='description')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='date create')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
            options={
                'verbose_name': 'bot',
                'verbose_name_plural': 'bots',
            },
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_message', models.TextField(blank=True, max_length=512, null=True, verbose_name='start message')),
                ('status', models.CharField(default='pending', max_length=25, verbose_name='status')),
                ('container_id', models.CharField(max_length=128, null=True, verbose_name='container_id')),
                ('params', models.JSONField(null=True, verbose_name='params')),
                ('is_fio', models.BooleanField(default=True, verbose_name='is_fio')),
                ('is_phone', models.BooleanField(default=True, verbose_name='is_phone')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
        ),
    ]
