# Generated by Django 4.2.2 on 2023-06-12 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='name')),
                ('img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image')),
                ('token', models.CharField(max_length=256, unique=True, verbose_name='token')),
                ('lang', models.CharField(blank=True, default='RUS', max_length=5, verbose_name='language')),
                ('desc', models.CharField(blank=True, max_length=512, verbose_name='description')),
                ('date_create', models.DateField(auto_now_add=True, verbose_name='date create')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'bot',
                'verbose_name_plural': 'bots',
            },
        ),
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(default=True, verbose_name='primary')),
                ('secondary', models.BooleanField(default=True, verbose_name='secondary')),
                ('start_message', models.TextField(blank=True, max_length=512, verbose_name='start message')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
        ),
    ]
