# Generated by Django 4.2.2 on 2023-08-06 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='botsettings',
            index=models.Index(fields=['id'], name='bots_botset_id_b71a89_idx'),
        ),
        migrations.AddIndex(
            model_name='botsettings',
            index=models.Index(fields=['bot'], name='bots_botset_bot_id_e85d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['id'], name='bots_bot_id_0824e5_idx'),
        ),
        migrations.AddIndex(
            model_name='bot',
            index=models.Index(fields=['admin'], name='bots_bot_admin_i_ce5cde_idx'),
        ),
    ]
