# Generated by Django 4.2.2 on 2023-07-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56, verbose_name='name')),
                ('surname', models.CharField(max_length=56, verbose_name='surname')),
                ('img', models.ImageField(blank=True, upload_to='rating/%Y/%m/%d/', verbose_name='image')),
                ('stars', models.DecimalField(decimal_places=0, max_digits=1, verbose_name='stars')),
                ('desc', models.CharField(blank=True, max_length=256, verbose_name='description')),
                ('label', models.CharField(default='Врач-педиатр', max_length=256, verbose_name='label name')),
            ],
            options={
                'verbose_name': 'rating',
                'verbose_name_plural': 'ratings',
            },
        ),
    ]
