# Generated by Django 4.2.2 on 2023-07-28 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='scenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultations.scenario'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='botusers.botusers'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['id'], name='consultatio_id_fb5f66_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['bot'], name='consultatio_bot_id_e979d3_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['start_time', 'expert'], name='consultatio_start_t_27a971_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['expert'], name='consultatio_expert__b5fda7_idx'),
        ),
    ]
