# Generated by Django 4.2.2 on 2023-06-12 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый проект', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('send_type', models.CharField(default='all', max_length=15)),
                ('report_message', models.BooleanField(default=True)),
                ('report_message_type', models.CharField(default='all', max_length=15)),
                ('admin_send_type', models.CharField(default='published', max_length=32)),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=32)),
                ('bots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
