# Generated by Django 4.2.2 on 2023-06-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новый проект', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('send_type', models.CharField(default='all', max_length=15)),
                ('report_message', models.BooleanField(default=True)),
                ('report_message_type', models.CharField(default='all', max_length=15)),
                ('admin_send_type', models.CharField(default='published', max_length=32)),
                ('timezone', models.CharField(default='Europe/Moscow', max_length=32)),
            ],
        ),
    ]
