# Generated by Django 4.2.2 on 2023-06-12 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('username', models.CharField(max_length=64)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_interation_date', models.DateTimeField(auto_now=True, null=True)),
                ('total_messages_recieved', models.PositiveIntegerField(default=0)),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('is_have_consultation', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
            options={
                'unique_together': {('bot', 'username')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=512)),
                ('is_read', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_author', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(max_length=10)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.botusers')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField(default=None)),
                ('sender_id', models.IntegerField(default=None)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bot', to='bots.bot')),
                ('messages', models.ManyToManyField(blank=True, to='chats.message')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('chat_id', 'user', 'bot')},
            },
        ),
    ]
