# Generated by Django 4.2.2 on 2023-07-28 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(default=None, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=512, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='messages/%Y/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='messages/%Y/')),
                ('video', models.FileField(blank=True, null=True, upload_to='messages/%Y/')),
                ('is_read', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('is_author', models.BooleanField(default=False)),
                ('is_bot', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['id'], name='chats_messa_id_b12c10_idx')],
            },
        ),
    ]
