# Generated by Django 4.2.2 on 2023-07-24 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('surname', models.CharField(blank=True, max_length=64, null=True)),
                ('username', models.CharField(max_length=64)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_have_consultation', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('params', models.JSONField(null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='botusers/avatars/%Y/')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
            options={
                'indexes': [models.Index(fields=['bot', 'username'], name='botusers_bo_bot_id_5ecd99_idx')],
                'unique_together': {('bot', 'username')},
            },
        ),
    ]
