# Generated by Django 4.2.2 on 2023-07-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsersStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages_recieved', models.PositiveIntegerField(default=0)),
                ('total_messages_sent', models.PositiveIntegerField(default=0)),
                ('last_interation_date', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, null=True)),
                ('last_name', models.CharField(max_length=64, null=True)),
                ('username', models.CharField(max_length=64)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('is_have_consultation', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('params', models.JSONField(null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
            options={
                'unique_together': {('bot', 'username')},
            },
        ),
    ]
