# Generated by Django 4.2.2 on 2023-08-06 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('telegram_id', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('agreement_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Self',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=32)),
                ('number', models.CharField(max_length=32)),
                ('issued_place', models.CharField(max_length=64)),
                ('issued_date', models.DateField()),
                ('division_code', models.CharField(max_length=32)),
                ('scan_current', models.FileField(upload_to='')),
                ('adress', models.CharField(max_length=128)),
                ('bank_acc', models.CharField(max_length=32)),
                ('bank_name', models.CharField(max_length=128)),
                ('bank_inn', models.CharField(max_length=32)),
                ('bank_bic', models.CharField(max_length=64)),
                ('cor_acc', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='in progress', max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.account')),
                ('consultation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.scenario')),
            ],
        ),
    ]
