# Generated by Django 4.2.2 on 2023-08-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='self',
            name='scan_self',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='self',
            name='scan_current',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
