# Generated by Django 4.2.2 on 2023-08-06 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_self_scan_self_alter_self_scan_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self',
            name='adress',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='self',
            name='bank_acc',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='self',
            name='bank_bic',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='self',
            name='bank_inn',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='self',
            name='bank_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='self',
            name='cor_acc',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='self',
            name='division_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='self',
            name='issued_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='self',
            name='issued_place',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='self',
            name='number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='self',
            name='scan_current',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='self',
            name='scan_self',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='self',
            name='series',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='self',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
