# Generated by Django 4.2.2 on 2023-08-06 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_alter_self_adress_alter_self_bank_acc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=32)),
                ('ogrn', models.CharField(max_length=32)),
                ('bank_acc', models.CharField(max_length=32)),
                ('bank_name', models.CharField(max_length=128)),
                ('bank_inn', models.CharField(max_length=32)),
                ('bank_bic', models.CharField(max_length=64)),
                ('cor_acc', models.CharField(max_length=128)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
