# Generated by Django 4.2.2 on 2023-07-29 14:26

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[apps.users.models.validate_unique_email], verbose_name='email'),
        ),
    ]
